apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sticky-layout
  description: he Sticky Layout app provides layout structures to help building
    elements that should be fixed relative to the viewport in certain contexts.
  tags:
    - typescript
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex-apps/sticky-layout
    vtex.com/platform-flow-id: ""
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: Y242Y1B1
spec:
  lifecycle: stable
  owner: te-0013
  type: frontend-ui
  dependsOn: []
